INSERT INTO `companies` (`name`) VALUES ('AA Motors');

INSERT INTO `branches` (`id`, `company_id`, `name`, `address_p`, `address_s`, `telephone`, `cellphone`, `city`, `created_at`, `updated_at`) VALUES
(1, 1, 'AA Motors Los Angeles', 'Direccion Principal', '\'\'', '2290229058', '7290229058', 'LA', '2022-01-13 23:25:13', '2022-01-13 23:25:13');

INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Users', 'CRUD Users', 'user', '1','fa-id-card-o');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Makes', 'CRUD Makes', 'make', '1','fa-cubes');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Models', 'CRUD Model', 'model', '1','fa-scribd');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Trims', 'CRUD Trim', 'trim', '1','fa-cogs');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Styles', 'CRUD Style', 'style', '1','fa-ship');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Config', 'CRUD Config', 'config_app', '1','fa-cog');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Cars', 'CRUD Cars', 'car', '2','fa-car');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Customer', 'CRUD Customer', 'customer', '2','fa-users');
INSERT INTO `options_app` (`name`, `description`, `path_option`, `group_option`, `icono`) VALUES ('Car Loans', 'CRUD Sales', 'loan', '2','fa-university');

INSERT INTO `users` (`id`,`branch_id`, `first_name`, `last_name`, `email`, `cargo`,`email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES(1,1, 'Edwin', 'Figueroa', 'edwin@gmail.com', 'Gerente',NULL, '$2y$10$gRSW26vzbFjm9gZJjTNY8.HdZhaWj0zhiZ5K3n4HUe/l6ZQp063yS', NULL, '2022-01-13 23:12:34', '2022-01-13 23:12:34');
INSERT INTO `users` (`id`,`branch_id`, `first_name`, `last_name`, `email`, `cargo`,`email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES(2,1, 'Operaciones', 'Automaticas', 'info@aamotorsla.com', 'Operador',NULL, '$2y$10$gRSW26vzbFjm9gZJjTNY8.HdZhaWj0zhiZ5K3n4HUe/l6ZQp063yS', NULL, '2022-01-13 23:12:34', '2022-01-13 23:12:34');

INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,1);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,2);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,3);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,4);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,5);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,6);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,7);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,8);
INSERT INTO `user_optios`(`user_id`, `option_id`) values (1,9);

insert into `configs` (`branch_id`,`long_term_default`,`porc_downpay_default`,`int_rate_default`,`latefee_default`,`dayslate_default`,`taxes_rate_default`) values(1,4,20,5.9,50,10,13.5);

INSERT INTO `states` (`name`) VALUES ('Alabama');
INSERT INTO `states` (`name`) VALUES ('Alaska');
INSERT INTO `states` (`name`) VALUES ('Arizona');
INSERT INTO `states` (`name`) VALUES ('Arkansas');
INSERT INTO `states` (`name`) VALUES ('California');
INSERT INTO `states` (`name`) VALUES ('Colorado');
INSERT INTO `states` (`name`) VALUES ('Connecticut');
INSERT INTO `states` (`name`) VALUES ('Delaware');
INSERT INTO `states` (`name`) VALUES ('Florida');
INSERT INTO `states` (`name`) VALUES ('Georgia');
INSERT INTO `states` (`name`) VALUES ('Hawaii');
INSERT INTO `states` (`name`) VALUES ('Idaho');
INSERT INTO `states` (`name`) VALUES ('Illinois');
INSERT INTO `states` (`name`) VALUES ('Indiana');
INSERT INTO `states` (`name`) VALUES ('Iowa');
INSERT INTO `states` (`name`) VALUES ('Kansas');
INSERT INTO `states` (`name`) VALUES ('Kentucky');
INSERT INTO `states` (`name`) VALUES ('Louisiana');
INSERT INTO `states` (`name`) VALUES ('Maine');
INSERT INTO `states` (`name`) VALUES ('Maryland');
INSERT INTO `states` (`name`) VALUES ('Massachusetts');
INSERT INTO `states` (`name`) VALUES ('Michigan');
INSERT INTO `states` (`name`) VALUES ('Minnesota');
INSERT INTO `states` (`name`) VALUES ('Mississippi');
INSERT INTO `states` (`name`) VALUES ('Missouri');
INSERT INTO `states` (`name`) VALUES ('Montana');
INSERT INTO `states` (`name`) VALUES ('Nebraska');
INSERT INTO `states` (`name`) VALUES ('Nevada');
INSERT INTO `states` (`name`) VALUES ('New Hampshire');
INSERT INTO `states` (`name`) VALUES ('New Jersey');
INSERT INTO `states` (`name`) VALUES ('New Mexico');
INSERT INTO `states` (`name`) VALUES ('New York');
INSERT INTO `states` (`name`) VALUES ('North Carolina');
INSERT INTO `states` (`name`) VALUES ('North Dakota');
INSERT INTO `states` (`name`) VALUES ('Ohio');
INSERT INTO `states` (`name`) VALUES ('Oklahoma');
INSERT INTO `states` (`name`) VALUES ('Oregon');
INSERT INTO `states` (`name`) VALUES ('Pennsylvania');
INSERT INTO `states` (`name`) VALUES ('Rhode Island');
INSERT INTO `states` (`name`) VALUES ('South Carolina');
INSERT INTO `states` (`name`) VALUES ('South Dakota');
INSERT INTO `states` (`name`) VALUES ('Tennessee');
INSERT INTO `states` (`name`) VALUES ('Texas');
INSERT INTO `states` (`name`) VALUES ('Utah');
INSERT INTO `states` (`name`) VALUES ('Vermont');
INSERT INTO `states` (`name`) VALUES ('Virginia');
INSERT INTO `states` (`name`) VALUES ('Washington');
INSERT INTO `states` (`name`) VALUES ('West Virginia');
INSERT INTO `states` (`name`) VALUES ('Wisconsin');
INSERT INTO `states` (`name`) VALUES ('Wyoming');
